Symfony4/src/Entity/Users.php
<?php


namespace App\Entity;

use App\Validator\Constraints\ComplexPassword;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use InvalidArgumentException;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;


/**

 * @ORM\Table(name="users")
 * @ORM\Entity(repositoryClass="App\Repository\UsersRepository")
 * @UniqueEntity(fields={"email"}, message="user exists")
 */
class Users implements UserInterface, \Serializable
{
    /**
     * @var int
     *
     * @ORM\Column(name="Id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @Groups("meet:search", "meet:index", "helpers:index", "meet:student","post:index")
     */
    private $id;
    /**
     * @Groups("meet:search")
     * @ORM\Column(type="string", length=60, unique=true)
     * @Assert\NotBlank(groups={"Registration"})
     * @Assert\Email()
     */
    private $email;


    /**
     * @ORM\Column(type="string", length=64)
     * @Assert\NotBlank(groups={"Registration", "PasswordReset"})
     * @Assert\Length(min="6")
     * @ComplexPassword()
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;


    /**
     * @var string|null
     *
     * @Groups("helpers:index", "meet:student", "meet:search")
     * @ORM\Column(name="username", type="string", length=255, nullable=true)
     * @Groups("post:index")
     * @Groups("quizz","quizz_result")
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $firstName;

    /**
     * @return string|null
     */
    public function getPseudo()
    {
        return $this->pseudo;
    }

    /**
     * @param string|null $pseudo
     */
    public function setPseudo($pseudo)
    {
        $this->pseudo = $pseudo;
    }

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $token;
    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="date")
     */
    private $dateOfBirth;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $activatedAt;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $phone;
    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $imageName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;
    /**
     * @var string
     *
     * @ORM\Column(name="about", type="string", length=255, nullable=true)
     */
    private $about;
//TODO : To change in Desktop Application by Array of roles
    /**
     * @var int
     *
     * @ORM\Column(name="role", type="integer", nullable=false)
     */
    private $role = '0';

    /**
     * @var array
     * @ORM\Column(type="array")
     */
    private $roles;
    /**
     * @var string|null
     *
     * @Groups("helpers:index")
     * @ORM\Column(name="Specialty", type="string", length=255, nullable=true)
     */
    private $specialty;

    /**
     * @var string|null
     *
     * @ORM\Column(name="code", type="string", length=255, nullable=true)
     */
    private $code;

    /**
     * @return string
     */
    public function getAbout()
    {
        return $this->about;
    }

    /**
     * @param string $about
     */
    public function setAbout($about)
    {
        $this->about = $about;
    }

    /**
     * @return int
     */
    public function getRole(): int
    {
        return $this->role;
    }

    /**
     * @param int $role
     */
    public function setRole($role)
    {
        $this->role = $role;
    }

    /**
     * @return string|null
     */
    public function getSpecialite()
    {
        return $this->specialty;
    }

    /**
     * @param string|null $specialty
     */
    public function setSpecialite(?string $specialty)
    {
        $this->specialty = $specialty;
    }

    /**
     * @return string|null
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * @param string|null $code
     */
    public function setCode(?string $code)
    {
        $this->code = $code;
    }

    public function getImageName()
    {
        return $this->imageName;
    }

    public function setImageName(string $imageName)
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getAdresse()
    {
        return $this->adresse;
    }

    /**
     * @param mixed $adresse
     */
    public function setAdresse($adresse)
    {
        $this->adresse = $adresse;
    }


    public function __construct()
    {
        $this->quizzs = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->firstName;
    }


    /**
     * @param mixed $firstName
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * @param mixed $lastName
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;
    }

    /**
     * @return mixed
     */
    public function getDateOfBirth()
    {
        return $this->dateOfBirth;
    }

    /**
     * @param mixed $dateOfBirth
     */
    public function setDateOfBirth($dateOfBirth)
    {
        $this->dateOfBirth = $dateOfBirth;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param mixed $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return mixed
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @param mixed $updatedAt
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * @return mixed
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * @param mixed $phone
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;
    }

    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password = $password;
    }

    /**
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param string $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }

    /**
     * @return bool
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * @param bool $isActive
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;
    }


    /**
     * @return mixed
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * @param mixed $token
     */
    public function setToken($token)
    {
        $this->token = $token;
    }

    /**
     * @param mixed $activatedAt
     */
    public function setActivatedAt($activatedAt)
    {
        $this->activatedAt = $activatedAt;
    }

    public function getRoles(): array
    {
        return $this->roles;
    }

    public function setRoles(array $roles): Users
    {
        if (!in_array('ROLE_USER', $roles)) {
            $roles[] = 'ROLE_USER';
        }
        foreach ($roles as $role) {
            if (substr($role, 0, 5) !== 'ROLE_') {
                throw new InvalidArgumentException("Chaque rôle doit commencer par 'ROLE_'");
            }
        }
        $this->roles = $roles;
        return $this;
    }


    /**
     * @param string|null $username
     */
    public function setUsername($username)
    {
        $this->username = $username;
    }
    /**
     * @return string
     */
    public function getUsername()
    {
        return $this->getEmail();
    }

    /**
     * @return string|null
     */
    public function getSpecialty(): ?string
    {
        return $this->specialty;
    }

    /**
     * @param string|null $specialty
     */
    public function setSpecialty(?string $specialty): void
    {
        $this->specialty = $specialty;
    }


    public function getSalt()
    {
        return null;
    }

    public function eraseCredentials()
    {
    }


    public function isAccountNonExpired()
    {
        return true;
    }

    public function isAccountNonLocked()
    {
        return true;
    }

    public function isCredentialsNonExpired()
    {
        return true;
    }

    /**
     * @return bool
     */
    public function isEnabled()
    {
        return $this->isActive;
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->email,
            $this->firstName,
            $this->lastName,
            $this->pseudo,
            $this->phone,
            $this->roles,

Symfony4/src/Controller/AdminControllers/AdminController.php
<?php

namespace App\Controller\AdminControllers;

use App\Entity\Post;
use App\Form\Post1Type;
use App\Repository\CommentRepository;
use App\Repository\PostRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/adminUser")
 */
class AdminController extends AbstractController
{
    /**
     * @Route("/", name="admin_homepage", methods={"GET"})
     */
    public function index(): Response
    {
        return $this->render('indexAdmin.html.twig');
    }


}

Symfony4/src/Controller/AdminControllers/AdminMeetController.php
<?php

namespace App\Controller\AdminControllers;

use App\Entity\Meet;
use App\Entity\Users;
use App\Form\MeetType;
use App\Repository\MeetRepository;
use App\Repository\UserRepository;
use Ramsey\Uuid\Uuid;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

/**
 * @Route("/admin/meet")
 * @IsGranted("ROLE_ADMIN")
 */
class AdminMeetController extends AbstractController
{
    /**
     * @Route("/", name="admin_meet", methods={"GET"})
     */
    public function index(MeetRepository $meetRepository): Response
    {
        return $this->render('admin_controllers/meet/index.html.twig', [
            'meets' => $meetRepository->findAll(),
        ]);
    }

    /**
     * @Route("/calendar", name="admin_calendar", methods={"GET"})
     */
    public function calendar(MeetRepository $meetRepository): Response
    {
        return $this->render('admin_controllers/meet/calendar.html.twig', [
            'meets' => $meetRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new/{id}", name="meet_new", methods={"GET","POST"})
     */
    public function new(Request $request, Users $user): Response
    {
        //$helperId = $request->query->get('user');
        //$helper = $userRepo->findOneBy(['id'=>$helperId]);
        $meet = new Meet();

        $meet->setIdHelper($user);
        $meet->setIdStudent($user);

        $meet->setSpecialite($user->getSpecialite());

        $form = $this->createForm(MeetType::class, $meet,array(
        ));
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            //updateDisponibilite
            $disponibilite = $form["disponibilite"]->getData();
            $disponibilite->setEtat(1);

            $entityManager->persist($meet);
            $entityManager->persist($disponibilite);

            $entityManager->flush();



            return $this->redirectToRoute('meet_index');
        }

        return $this->render('user_controllers/meet/new.html.twig', [
            'meet' => $meet,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="meet_show", methods={"GET"})
     */
    public function show(Meet $meet): Response
    {
        return $this->render('user_controllers/meet/show.html.twig', [
            'meet' => $meet,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="meet_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Meet $meet): Response
    {
        $form = $this->createForm(MeetType::class, $meet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('meet_index');
        }

        return $this->render('user_controllers/meet/edit.html.twig', [
            'meet' => $meet,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="meet_delete", methods={"POST"})
     */
    public function delete(Request $request, Meet $meet): Response
    {
        if ($this->isCsrfTokenValid('delete'.$meet->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($meet);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_meet');
    }

    /**
     * @Route("/search", name="admin_meet_search", methods={"GET"})
     */
    public function search(Request $request, MeetRepository $meetRepository, NormalizerInterface $normalizer): Response
    {
        $filter = $request->query->get('filter');
        $meets = $meetRepository->search($filter);
        if(sizeof($meets)>0) {
            $json_meets = $normalizer->normalize($meets, 'json', ['groups'=>'meet:search']);
            // Send all this back to client
            return new JsonResponse(array(
                'status' => 'OK',
                'data' => $json_meets),
                200);
        }
        return new JsonResponse(array(
            'status' => 'ERROR',
            'data' => 'not found'),
            200);
    }
}

Symfony4/src/Controller/AdminControllers/AnswerController.php
<?php

namespace App\Controller\AdminControllers;

use App\Entity\Answer;
use App\Entity\Question;
use App\Entity\Quizz;
use App\Form\AnswerFormType;
use App\Form\QuestionEditFormType;
use App\Form\QuestionFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/admin/quiz")
 */
class AnswerController extends AbstractController
{
    /**
     * @Route("/{id}/questions/{qId}/answers", name="admin_answer_list")
     */
    public function list($id,$qId,EntityManagerInterface $em): Response
    {
        $repository = $em->getRepository(Quizz::class);

        $quiz = $repository->findOneBy(
            ['id' => $id]
        );

        $repository = $em->getRepository(Question::class);

        $question = $repository->findOneBy(
            ['id' => $qId]
        );

        $answers = $question->getAnswers();

        return $this->render('admin_controllers/answer/list.html.twig', [
            'answers' => $answers,
            'question' => $question,
            'quizzId' => $id,
            'questionId' => $qId,
        ]);
    }

    /**
     * @Route("/{id}/question/{qId}/answer/{aId}/delete", name="admin_answer_delete")
     */
    public function delete($id,$qId,$aId,EntityManagerInterface $em,Request $request)
    {
        $repo = $em->getRepository(Answer::class);

        $answer= $repo->findOneBy([
            'id' => $aId
        ]);

        $title = $answer->getSuggestion();

        $em->remove($answer);
        $em->flush();

        $this->addFlash('failure','Answer '.$title.' was removed from your possible Answers.');

        return $this->redirectToRoute('admin_answer_list',['id'=>$id,'qId'=>$qId]);
    }
}

Symfony4/templates/admin_controllers/meet/_delete_form.html.twig
<form method="post" action="{{ path('meet_delete', {'id': meet.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ meet.id) }}">
    <button class="btn btn-sm btn-primary">Delete</button>
</form>

Symfony4/templates/admin_controllers/meet/_form.html.twig
{{ form_start(form) }}
    <div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label>{{ form_label(form.specialite)}}</label>
            {{ form_widget(form.specialite) }}
        </div>
    </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label>{{ form_label(form.idHelper)}}</label>
                {{ form_widget(form.idHelper) }}
            </div>
        </div>
    </div>
    <div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label>{{ form_label(form.disponibilite)}}</label>
            {{ form_widget(form.disponibilite) }}
        </div>
    </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
            {{ form_widget(form.Save) }}
            </div>
        </div>
    </div>
{{ form_end(form) }}

Symfony4/templates/admin_controllers/meet/calendar.html.twig
<!DOCTYPE html>
<html>
<head>

    <link rel="stylesheet" href="{{ asset('assets/css/calendar/fullcalendar.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/calendar/calendar.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/calendar/style.min.css') }}">
    <title>Simpalha meets calendar</title>
</head>

<body>
<!-- EDIT EVENT MODAL -->

<div class="modal fade" tabindex="-1" role="dialog" id="editEventModal">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header" style="margin: auto">
                <h4 class="modal-title">Meet details <span class="eventName"></span></h4>
            </div>
            <div class="modal-body">

                <div class="col-md-8 mx-auto">
                    <div class="form-group">
                        <label>Helper: </label>
                        <label id="helperIdtext"></label>

                    </div>
                </div>
                <div class="col-md-8 mx-auto">
                    <div class="form-group">
                        <label>Student: </label>
                        <label id="studentIdtext"></label>

                    </div>
                </div>
                <div class="col-md-8 mx-auto">
                    <div class="form-group">
                        <label>Specialite: </label>
                        <label id="specialiteIdtext"></label>

                    </div>
                </div>
                <div class="col-md-8 mx-auto">
                    <div class="form-group">
                        <label>Date: </label>
                        <label id="datetext"></label>

                    </div>
                </div>
                <div class="col-md-8 mx-auto">
                    <div class="form-group">
                        <label>Status: </label>
                        <label id="statustext"></label>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="container-fluid mt--6">
        <div class="row justify-content-center">
            <div class=" col ">
                <div class="card">
                    <div class="card-header bg-transparent">
                        <h3 class="mb-0">MeetIndex</h3>
                    </div>
                    <div class="card-body">
                        <div style="text-align: right">
                            <input type="search" id="search" placeholder="Search.." name="search" class="search">
                        </div>
                        <div class="print-visible" id="calendar"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>



<script src="{{ asset("assets/js/calendar/jquery.min.js") }}"></script>
<script src="{{ asset("assets/js/calendar/bootstrap.min.js") }}"></script>

    <script src="{{ asset("assets/js/calendar/moment.js") }}"></script>
    <script src="{{ asset("assets/js/calendar/locale-all.js") }}"></script>
    <script src="{{ asset("assets/js/calendar/fullcalendar.min.js") }}"></script>
    <script>
        var events = [];
        var editEvent;
        var newEvent;
        var filterpath = '{{ path('admin_meet_search') }}';


        function fillCalendar() {
            {% for meet in meets %}
            events.push({
                _id: '{{ meet.id }}',
                title: 'Helper '+ '{{ meet.idHelper.pseudo }}' + " meet with "+'{{ meet.idStudent.pseudo }}',
                avatar: "",
                etat:'{{ meet.etat }}',
                description:
                    'Helper '+ '{{ meet.idHelper.pseudo }}' + " meet with "+'{{ meet.idStudent.pseudo }}',
                start: moment('{{meet.disponibilite.datedeb|date('y-m-d h:i:s')}}','YYYY-MM-DD HH:mm:ss'),
                end: moment('{{meet.disponibilite.datefin|date('d-m-y h:i:s') }}','YYYY-MM-DD HH:mm:ss'),
                type: "Appointment",
                calendar: "",
                className: "colorAppointment",
                student: '{{ meet.idStudent.pseudo }}',
                specialite: '{{ meet.specialite }}',
                helper: '{{ meet.idHelper.pseudo }}',
                backgroundColor: "#f4516c",
                textColor: "#ffffff",
                allDay: false,
            });
            {% endfor %}
            console.log(events);
}

fillCalendar();

</script>
<script src="{{ asset("assets/js/calendar/calendar.js") }}"></script>


</body>
</html>

Symfony4/templates/admin_controllers/meet/edit.html.twig
{% extends 'baseUser.html.twig' %}
{% block title %}New Meet{% endblock %}

{% block body %}
    <div class="container">
        <div class="row mb-4 mr-1 pb-4">
            <div class="col-12 mb-3">
                <a href="{{ path('meet_index') }}"><button type="button" class="btn waves-effect waves-light btn-lg btn-primary">
                        &nbsp; Retour</button></a>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Create new Meet</h4>
                        <div class="card-block">
                            {{ include('user_controllers/meet/_form.html.twig') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Symfony4/templates/admin_controllers/meet/index.html.twig
{% extends 'baseAdmin.html.twig' %}
{% block title %}Meet index{% endblock %}


{% block body %}
    <div class="container-fluid" style="margin-top: 10%;">
        <div class="row justify-content-center">
            <div class=" col ">
                <div class="card">
                    <div class="card-header bg-transparent row">
                        <div class="col-6">
                            <h3 class="mb-0">MeetIndex</h3>
                        </div>
                        <div class="col-6" style="text-align: end">
                            <h3 class="mb-0"><a target="_blank" href="{{ path('admin_calendar') }}">Calendar</a></h3>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
    <table id="default_order" class="table align-items-center table-flush">
        <thead class="thead-light">
            <tr>
                <th>Helper</th>
                <th>Specialite</th>
                <th>Feedback</th>
                <th>Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for meet in meets %}
            <tr>
                <td>{{ meet.idHelper.pseudo }}</td>
                <td>{{ meet.specialite }}</td>
                <td>{% if meet.feedback is not null %}
                        {{ meet.feedback.description }}</td>
                    {% endif %}
                <td>{{ meet.disponibilite.datedeb|date('d-m-y h:i') }}</td>
                <td>
                    {{ include('admin_controllers/meet/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

        {% endblock %}
{% block scripts %}
{{ parent() }}
    <script src="{{ asset("assets/js/datatable/jquery.dataTables.min.js") }}"></script>
    <script src="{{ asset("assets/js/datatable/datatable-basic.init.js") }}"></script>
{% endblock %}

Symfony4/templates/admin_controllers/meet/new.html.twig
{% extends 'baseUser.html.twig' %}
{% block title %}New Meet{% endblock %}

{% block body %}
    <div class="container">
        <div class="row mb-4 mr-1 pb-4">
            <div class="col-12 mb-3">
                <a href="{{ path('meet_index') }}"><button type="button" class="btn waves-effect waves-light btn-lg btn-primary">
                        &nbsp; Retour</button></a>
            </div>
        </div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Create new Meet</h4>
                <div class="card-block">
                {{ include('user_controllers/meet/_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>
</div>
    </div>
{% endblock %}

Symfony4/templates/admin_controllers/meet/show.html.twig
<!DOCTYPE html>

<title>Meet</title>

{% block body %}
    <h1>Meet</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Specialite</th>
                <td>{{ meet.specialite }}</td>
            </tr>
            <tr>
                <th>Etat</th>
                <td>{{ meet.etat }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('meet_index') }}">back to list</a>

    <a href="{{ path('meet_edit', {'id': meet.id}) }}">edit</a>

    {{ include('user_controllers/meet/_delete_form.html.twig') }}
{% endblock %}